# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-02-12 22:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=120, verbose_name='T\xfcr')),
                ('breed', models.CharField(max_length=120, verbose_name='Cins')),
                ('name', models.CharField(max_length=60, verbose_name='Ad')),
                ('age', models.PositiveIntegerField(verbose_name='Ya\u015f')),
                ('description', models.TextField(verbose_name='A\xe7\u0131klama')),
                ('image', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL, verbose_name='Hayvan Sahibi')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
